import PDFDocument from 'pdfkit'

const DARK_BLUE = '#1e3a5f'
const ACCENT_BLUE = '#2563eb'
const DARK_GRAY = '#374151'
const LIGHT_GRAY = '#6b7280'

function buildPdf(doc, data) {
  const { scanId, fileName, date, score, status } = data
  const dateFormatted = new Date(date).toLocaleString(undefined, {
    dateStyle: 'long',
    timeStyle: 'medium',
  })
  const biometricScore = Math.round(100 - score)
  const vocalScore = Math.round(100 - score)

  let y = 60

  doc
    .fontSize(28)
    .fillColor(DARK_BLUE)
    .font('Helvetica-Bold')
    .text('VerifEye', 50, y)
  y += 40

  doc
    .fontSize(10)
    .fillColor(LIGHT_GRAY)
    .font('Helvetica')
    .text('Forensic Media Verification Report', 50, y)
  y += 30

  doc
    .rect(50, y, 495, 2)
    .fillColor(DARK_BLUE)
    .fill()
  y += 25

  doc
    .fontSize(11)
    .fillColor(DARK_GRAY)
    .font('Helvetica-Bold')
    .text('Scan ID:', 50, y)
  doc.font('Helvetica').text(scanId, 150, y)
  y += 22

  doc.font('Helvetica-Bold').text('Date & Time:', 50, y)
  doc.font('Helvetica').text(dateFormatted, 150, y)
  y += 22

  doc.font('Helvetica-Bold').text('Filename:', 50, y)
  doc.font('Helvetica').text(fileName || '—', 150, y)
  y += 28

  doc
    .fontSize(12)
    .fillColor(DARK_BLUE)
    .font('Helvetica-Bold')
    .text('Final Result', 50, y)
  y += 22

  const resultColor = status === 'REAL' ? '#059669' : '#dc2626'
  doc
    .fontSize(18)
    .fillColor(resultColor)
    .font('Helvetica-Bold')
    .text(status, 50, y)
  doc
    .fontSize(10)
    .fillColor(LIGHT_GRAY)
    .font('Helvetica')
    .text(`Deepfake probability: ${score}%`, 120, y + 4)
  y += 35

  doc
    .rect(50, y - 2, 495, 28)
    .fillColor('#f1f5f9')
    .fill()
  doc
    .rect(50, y - 2, 495, 28)
    .strokeColor(DARK_BLUE)
    .lineWidth(0.5)
    .stroke()
  doc
    .fontSize(12)
    .fillColor(DARK_BLUE)
    .font('Helvetica-Bold')
    .text('Analysis Breakdown', 60, y + 6)
  y += 35

  doc
    .rect(50, y, 495, 35)
    .fillColor('#f8fafc')
    .fill()
  doc
    .rect(50, y, 495, 35)
    .strokeColor('#e2e8f0')
    .lineWidth(0.5)
    .stroke()
  doc
    .fontSize(10)
    .fillColor(DARK_GRAY)
    .font('Helvetica-Bold')
    .text('Biometric Integrity', 60, y + 12)
  doc
    .font('Helvetica')
    .fillColor(LIGHT_GRAY)
    .text(status === 'REAL' ? 'Analysis complete: No AI cloning detected' : 'Analysis complete: AI manipulation indicators present', 60, y + 26)
  doc
    .fillColor(ACCENT_BLUE)
    .font('Helvetica-Bold')
    .text(`${biometricScore}%`, 480, y + 12, { width: 50, align: 'right' })
  y += 45

  doc
    .rect(50, y, 495, 35)
    .fillColor('#f8fafc')
    .fill()
  doc
    .rect(50, y, 495, 35)
    .strokeColor('#e2e8f0')
    .lineWidth(0.5)
    .stroke()
  doc
    .fontSize(10)
    .fillColor(DARK_GRAY)
    .font('Helvetica-Bold')
    .text('Vocalic Imprint', 60, y + 12)
  doc
    .font('Helvetica')
    .fillColor(LIGHT_GRAY)
    .text(status === 'REAL' ? 'Analysis complete: Lip sync verified' : 'Analysis complete: Vocal inconsistency detected', 60, y + 26)
  doc
    .fillColor(ACCENT_BLUE)
    .font('Helvetica-Bold')
    .text(`${vocalScore}%`, 480, y + 12, { width: 50, align: 'right' })
  y += 50

  doc
    .fontSize(8)
    .fillColor(LIGHT_GRAY)
    .font('Helvetica')
    .text('Generated by VerifEye — Truth Layer. This report is for informational purposes only.', 50, y)
}

export function generatePdfBuffer(data) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 })
    const chunks = []
    doc.on('data', (chunk) => chunks.push(chunk))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    buildPdf(doc, data)
    doc.end()
  })
}
