import { useState, useEffect } from 'react'
import { useAuth } from '../context/AuthContext'
import { API_BASE } from '../config.js'
import { getScanHistory } from '../utils/scanHistory'
import LegalPage from '../components/LegalPage'

const APP_VERSION = '0.1.2-beta'

const FAQ_ITEMS = [
  {
    q: 'How does VerifEye detect deepfakes?',
    a: 'VerifEye uses AI-powered analysis to examine biometric consistency, vocal patterns, metadata, and other indicators of synthetic or manipulated media. Our algorithms assess the likelihood that content has been altered or generated by AI.',
  },
  {
    q: 'What are the scan limits?',
    a: 'Starter plans include 3 scans per month. Quick Boost adds 10 scans (refill anytime). Pro offers 50 scans/month, and Elite includes unlimited scans. Credits never expire for Quick Boost purchases.',
  },
  {
    q: 'How do PDF reports work?',
    a: 'Forensic PDF reports are available to Pro and Elite subscribers. Starter and Quick Boost users can upgrade to Pro or Elite to unlock PDF downloads from their scan history.',
  },
  {
    q: 'How do credits work?',
    a: 'Each scan consumes one credit. Starter gets 3 free scans per month. Quick Boost adds 10 scans per purchase. Pro resets to 50 scans each billing cycle. Elite has unlimited scans with no credit consumption.',
  },
  {
    q: 'What happens to my data and privacy?',
    a: 'Media files are processed for analysis only and are not permanently stored on our servers. Your scan history (file names, dates, results) is stored locally on your device. We do not sell or share your data. See our Privacy Policy for full details.',
  },
]

const BackIcon = () => (
  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
  </svg>
)

const TABS = [
  { id: 'profile', label: 'Profile' },
  { id: 'security', label: 'Security' },
  { id: 'subscription', label: 'Subscription' },
  { id: 'support', label: 'FAQ & Support' },
  { id: 'about', label: 'About & App Info' },
]

const DISPLAY_NAME_KEY = 'verifeye_displayname'

function getDisplayName(email) {
  try {
    const stored = localStorage.getItem(DISPLAY_NAME_KEY)
    if (stored) {
      const map = JSON.parse(stored)
      return map[email] || ''
    }
  } catch (_) {}
  return ''
}

function setDisplayName(email, name) {
  try {
    const stored = localStorage.getItem(DISPLAY_NAME_KEY) || '{}'
    const map = JSON.parse(stored)
    map[email] = name
    localStorage.setItem(DISPLAY_NAME_KEY, JSON.stringify(map))
  } catch (_) {}
}

export default function SettingsPage({ onBack }) {
  const { user, logout, refreshUser, getAuthHeaders } = useAuth()
  const [activeTab, setActiveTab] = useState('profile')
  const [displayName, setDisplayNameState] = useState('')
  const [displayNameSaved, setDisplayNameSaved] = useState(false)
  const [passwordForm, setPasswordForm] = useState({ current: '', new: '', confirm: '' })
  const [passwordError, setPasswordError] = useState('')
  const [passwordSuccess, setPasswordSuccess] = useState(false)
  const [passwordLoading, setPasswordLoading] = useState(false)
  const [deleteConfirm, setDeleteConfirm] = useState(false)
  const [deleteLoading, setDeleteLoading] = useState(false)
  const [legalView, setLegalView] = useState(null)
  const [faqOpen, setFaqOpen] = useState(null)
  const [contactForm, setContactForm] = useState({ name: '', message: '' })
  const [contactLoading, setContactLoading] = useState(false)
  const [contactSuccess, setContactSuccess] = useState(false)

  const email = user?.email || ''
  const scanCredits = user?.scanCredits ?? 0
  const subscriptionTier = user?.subscriptionTier ?? 'starter'
  const canContactSupport = subscriptionTier === 'pro' || subscriptionTier === 'elite'

  useEffect(() => {
    setDisplayNameState(getDisplayName(email))
  }, [email])

  const handleExportData = () => {
    const history = getScanHistory()
    const exportData = {
      exportDate: new Date().toISOString(),
      userEmail: email,
      scanHistory: history,
    }
    const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `verifeye-data-export-${new Date().toISOString().slice(0, 10)}.json`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const handleSaveDisplayName = () => {
    setDisplayName(email, displayName)
    setDisplayNameSaved(true)
    setTimeout(() => setDisplayNameSaved(false), 2000)
  }

  const handleChangePassword = async (e) => {
    e.preventDefault()
    setPasswordError('')
    setPasswordSuccess(false)
    if (passwordForm.new !== passwordForm.confirm) {
      setPasswordError('New passwords do not match')
      return
    }
    if (passwordForm.new.length < 6) {
      setPasswordError('New password must be at least 6 characters')
      return
    }
    setPasswordLoading(true)
    try {
      const res = await fetch(`${API_BASE}/api/auth/change-password`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...getAuthHeaders() },
        body: JSON.stringify({
          currentPassword: passwordForm.current,
          newPassword: passwordForm.new,
        }),
      })
      const data = await res.json()
      if (!data.success) throw new Error(data.error || 'Failed to change password')
      setPasswordSuccess(true)
      setPasswordForm({ current: '', new: '', confirm: '' })
    } catch (err) {
      setPasswordError(err.message)
    } finally {
      setPasswordLoading(false)
    }
  }

  const handleContactSubmit = async (e) => {
    e.preventDefault()
    if (!contactForm.name.trim() || !contactForm.message.trim()) return
    setContactLoading(true)
    setContactSuccess(false)
    try {
      // Simulated submit - in production, POST to /api/support
      await new Promise((r) => setTimeout(r, 800))
      setContactForm({ name: '', message: '' })
      setContactSuccess(true)
    } catch (err) {
      console.error(err)
    } finally {
      setContactLoading(false)
    }
  }

  const handleDeleteAccount = async () => {
    if (!deleteConfirm) return
    setDeleteLoading(true)
    try {
      const res = await fetch(`${API_BASE}/api/auth/delete-account`, {
        method: 'DELETE',
        headers: { 'Content-Type': 'application/json', ...getAuthHeaders() },
        body: JSON.stringify({ confirm: true }),
      })
      const data = await res.json()
      if (!data.success) throw new Error(data.error || 'Failed to delete account')
      logout()
    } catch (err) {
      setPasswordError(err.message)
    } finally {
      setDeleteLoading(false)
    }
  }

  if (legalView) {
    return <LegalPage type={legalView} onBack={() => setLegalView(null)} />
  }

  return (
    <div className="min-h-screen bg-[#0d0d0d] flex flex-col">
      <header className="flex items-center gap-3 px-4 py-4 border-b border-slate-800 shrink-0">
        <button
          onClick={onBack}
          className="p-2 text-white hover:bg-white/10 rounded-full transition-colors"
          aria-label="Back"
        >
          <BackIcon />
        </button>
        <h1 className="text-xl font-bold text-white">Settings</h1>
      </header>

      <div className="flex-1 flex overflow-hidden">
        <aside className="w-48 shrink-0 border-r border-slate-800 py-4 hidden sm:block">
          <nav className="space-y-0.5 px-2">
            {TABS.map((tab) => (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={`w-full text-left px-4 py-2.5 rounded-lg text-sm font-medium transition-colors ${
                  activeTab === tab.id
                    ? 'bg-cyan-500/20 text-cyan-400'
                    : 'text-slate-400 hover:text-white hover:bg-slate-800/50'
                }`}
              >
                {tab.label}
              </button>
            ))}
          </nav>
        </aside>

        <main className="flex-1 overflow-y-auto px-4 py-6 pb-24">
          <div className="max-w-xl mx-auto space-y-8">
            {/* Mobile tabs */}
            <div className="sm:hidden flex gap-2 overflow-x-auto pb-2 -mx-4 px-4">
              {TABS.map((tab) => (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id)}
                  className={`shrink-0 px-3 py-2 rounded-lg text-sm font-medium ${
                    activeTab === tab.id
                      ? 'bg-cyan-500/20 text-cyan-400'
                      : 'text-slate-400 bg-slate-800/50'
                  }`}
                >
                  {tab.label}
                </button>
              ))}
            </div>

            {/* Profile */}
            {activeTab === 'profile' && (
              <section>
                <h2 className="text-lg font-semibold text-white mb-4">Profile</h2>
                <div className="space-y-4">
                  <div>
                    <label className="block text-slate-400 text-sm mb-2">Display Name</label>
                    <input
                      type="text"
                      value={displayName}
                      onChange={(e) => setDisplayNameState(e.target.value)}
                      placeholder="Your display name"
                      className="w-full px-4 py-3 bg-slate-800/60 border border-slate-600 rounded-xl text-white placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-cyan-500/50"
                    />
                    <button
                      onClick={handleSaveDisplayName}
                      className="mt-2 px-4 py-2 bg-cyan-600 text-white text-sm font-medium rounded-lg hover:bg-cyan-500 transition-colors"
                    >
                      {displayNameSaved ? 'Saved ✓' : 'Save'}
                    </button>
                  </div>
                  <div>
                    <label className="block text-slate-400 text-sm mb-2">Registered Email</label>
                    <p className="px-4 py-3 bg-slate-800/40 border border-slate-700 rounded-xl text-slate-300">
                      {email}
                    </p>
                  </div>
                  <button
                    onClick={handleExportData}
                    className="w-full py-3 px-4 bg-slate-800/60 border border-slate-600 rounded-xl text-cyan-400 font-medium hover:bg-slate-700/60 transition-colors"
                  >
                    Export My Data
                  </button>
                  <button
                    onClick={logout}
                    className="text-red-400 hover:text-red-300 text-sm font-medium"
                  >
                    Log Out
                  </button>
                </div>
              </section>
            )}

            {/* Security */}
            {activeTab === 'security' && (
              <section>
                <h2 className="text-lg font-semibold text-white mb-4">Security</h2>
                <form onSubmit={handleChangePassword} className="space-y-4">
                  <div>
                    <label className="block text-slate-400 text-sm mb-2">Current Password</label>
                    <input
                      type="password"
                      value={passwordForm.current}
                      onChange={(e) => setPasswordForm((p) => ({ ...p, current: e.target.value }))}
                      className="w-full px-4 py-3 bg-slate-800/60 border border-slate-600 rounded-xl text-white focus:outline-none focus:ring-2 focus:ring-cyan-500/50"
                      required
                    />
                  </div>
                  <div>
                    <label className="block text-slate-400 text-sm mb-2">New Password</label>
                    <input
                      type="password"
                      value={passwordForm.new}
                      onChange={(e) => setPasswordForm((p) => ({ ...p, new: e.target.value }))}
                      className="w-full px-4 py-3 bg-slate-800/60 border border-slate-600 rounded-xl text-white focus:outline-none focus:ring-2 focus:ring-cyan-500/50"
                      minLength={6}
                      required
                    />
                  </div>
                  <div>
                    <label className="block text-slate-400 text-sm mb-2">Confirm New Password</label>
                    <input
                      type="password"
                      value={passwordForm.confirm}
                      onChange={(e) => setPasswordForm((p) => ({ ...p, confirm: e.target.value }))}
                      className="w-full px-4 py-3 bg-slate-800/60 border border-slate-600 rounded-xl text-white focus:outline-none focus:ring-2 focus:ring-cyan-500/50"
                      minLength={6}
                      required
                    />
                  </div>
                  {passwordError && <p className="text-red-400 text-sm">{passwordError}</p>}
                  {passwordSuccess && <p className="text-green-400 text-sm">Password updated successfully.</p>}
                  <button
                    type="submit"
                    disabled={passwordLoading}
                    className="px-4 py-2 bg-cyan-600 text-white font-medium rounded-lg hover:bg-cyan-500 disabled:opacity-50"
                  >
                    {passwordLoading ? 'Updating...' : 'Change Password'}
                  </button>
                </form>
                <div className="mt-12 pt-8 border-t border-slate-800">
                  <button
                    onClick={() => setDeleteConfirm(!deleteConfirm)}
                    className="mb-4 px-4 py-2 bg-red-600/20 text-red-400 border border-red-500/50 rounded-lg hover:bg-red-600/30 transition-colors"
                  >
                    {deleteConfirm ? 'Cancel Delete' : 'Delete Account'}
                  </button>
                  {deleteConfirm && (
                    <div className="space-y-2">
                      <p className="text-slate-400 text-sm">This action cannot be undone. All your data will be permanently deleted.</p>
                      <button
                        onClick={handleDeleteAccount}
                        disabled={deleteLoading}
                        className="px-4 py-2 bg-red-600 text-white font-medium rounded-lg hover:bg-red-500 disabled:opacity-50"
                      >
                        {deleteLoading ? 'Deleting...' : 'Confirm Delete Account'}
                      </button>
                    </div>
                  )}
                </div>
              </section>
            )}

            {/* Support & FAQ */}
            {activeTab === 'support' && (
              <section>
                <h2 className="text-lg font-semibold text-white mb-4">FAQ & Support</h2>

                <div className="space-y-3 mb-8">
                  {FAQ_ITEMS.map((item, i) => (
                    <div
                      key={i}
                      className="rounded-xl overflow-hidden border border-slate-700/50 bg-slate-800/30 backdrop-blur-xl shadow-lg"
                      style={{ boxShadow: '0 4px 24px rgba(0,0,0,0.15), inset 0 1px 0 rgba(255,255,255,0.03)' }}
                    >
                      <button
                        onClick={() => setFaqOpen(faqOpen === i ? null : i)}
                        className="w-full flex items-center justify-between px-4 py-3.5 text-left text-white font-medium hover:bg-slate-700/20 transition-colors"
                      >
                        <span className="text-sm pr-2">{item.q}</span>
                        <svg
                          className={`w-5 h-5 shrink-0 text-slate-400 transition-transform duration-200 ${faqOpen === i ? 'rotate-180' : ''}`}
                          fill="none"
                          stroke="currentColor"
                          viewBox="0 0 24 24"
                        >
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                        </svg>
                      </button>
                      {faqOpen === i && (
                        <div className="px-4 pb-4 pt-0 border-t border-slate-700/40">
                          <p className="text-slate-400 text-sm leading-relaxed pt-3">{item.a}</p>
                        </div>
                      )}
                    </div>
                  ))}
                </div>

                <div
                  className="rounded-xl border border-slate-700/50 bg-slate-800/30 backdrop-blur-xl p-4"
                  style={{ boxShadow: '0 4px 24px rgba(0,0,0,0.15), inset 0 1px 0 rgba(255,255,255,0.03)' }}
                >
                  <h3 className="text-white font-medium mb-3">Contact Us</h3>
                  {!canContactSupport ? (
                    <p className="text-slate-400 text-sm leading-relaxed">
                      Direct support is exclusive to Pro & Elite members. Please check the FAQs above for common questions, or upgrade your plan to access our support team.
                    </p>
                  ) : contactSuccess ? (
                    <p className="text-green-400 text-sm">Thank you! Your message has been sent. We&apos;ll get back to you soon.</p>
                  ) : (
                    <form onSubmit={handleContactSubmit} className="space-y-3">
                      <div>
                        <label className="block text-slate-400 text-sm mb-1.5">Name</label>
                        <input
                          type="text"
                          value={contactForm.name}
                          onChange={(e) => setContactForm((f) => ({ ...f, name: e.target.value }))}
                          placeholder="Your name"
                          className="w-full px-4 py-2.5 bg-slate-800/60 border border-slate-600 rounded-lg text-white placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-cyan-500/50 text-sm"
                          required
                        />
                      </div>
                      <div>
                        <label className="block text-slate-400 text-sm mb-1.5">Message</label>
                        <textarea
                          value={contactForm.message}
                          onChange={(e) => setContactForm((f) => ({ ...f, message: e.target.value }))}
                          placeholder="How can we help?"
                          rows={4}
                          className="w-full px-4 py-2.5 bg-slate-800/60 border border-slate-600 rounded-lg text-white placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-cyan-500/50 text-sm resize-none"
                          required
                        />
                      </div>
                      <button
                        type="submit"
                        disabled={contactLoading}
                        className="w-full py-2.5 px-4 bg-cyan-600 text-white font-medium rounded-lg hover:bg-cyan-500 transition-colors disabled:opacity-50 text-sm"
                      >
                        {contactLoading ? 'Sending...' : 'Submit'}
                      </button>
                    </form>
                  )}
                </div>
              </section>
            )}

            {/* Subscription */}
            {activeTab === 'subscription' && (
              <section>
                <h2 className="text-lg font-semibold text-white mb-4">Subscription</h2>
                <div className="p-6 bg-slate-800/60 border border-slate-700 rounded-xl">
                  <p className="text-slate-400 text-sm mb-1">Current Balance</p>
                  <p className="text-3xl font-bold text-cyan-400">{scanCredits}</p>
                  <p className="text-slate-500 text-sm mt-1">scan credits remaining</p>
                  <button
                    onClick={() => refreshUser()}
                    className="mt-4 w-full py-3 px-4 bg-gradient-to-r from-cyan-600 to-purple-600 text-white font-medium rounded-xl hover:opacity-90 transition-opacity"
                  >
                    Buy More Credits
                  </button>
                  <p className="text-slate-500 text-xs mt-2 text-center">Coming soon</p>
                </div>
              </section>
            )}

            {/* About & App Info */}
            {activeTab === 'about' && (
              <section>
                <h2 className="text-lg font-semibold text-white mb-4">About & App Info</h2>
                <p className="text-slate-300 text-sm leading-relaxed mb-6">
                  VerifEye is a leading platform for deepfake detection and media authentication.
                  Our AI-powered analysis helps you verify the authenticity of videos, images, and audio
                  in an era of increasingly sophisticated synthetic media. Trust the Truth Layer.
                </p>
                <div className="flex items-center gap-3 mb-6">
                  <span className="text-slate-400 text-sm">Version</span>
                  <span className="text-cyan-400 font-medium">VerifEye v{APP_VERSION}</span>
                  <button
                    className="px-3 py-1.5 text-xs bg-slate-800 border border-slate-600 rounded-lg text-slate-400 hover:text-white transition-colors"
                  >
                    Check for updates
                  </button>
                </div>
                <div className="flex flex-wrap gap-6 text-sm mb-8">
                  <button
                    onClick={() => setActiveTab('support')}
                    className="text-cyan-400 hover:text-cyan-300"
                  >
                    FAQ & Support
                  </button>
                  <button
                    onClick={() => setLegalView('privacy')}
                    className="text-cyan-400 hover:text-cyan-300"
                  >
                    Privacy Policy
                  </button>
                  <button
                    onClick={() => setLegalView('terms')}
                    className="text-cyan-400 hover:text-cyan-300"
                  >
                    Terms of Service
                  </button>
                </div>
                <div className="flex justify-center pt-4 opacity-40">
                  <div className="w-12 h-12 rounded-full bg-purple-600 flex items-center justify-center text-white font-bold text-xl">
                    V
                  </div>
                </div>
              </section>
            )}
          </div>
        </main>
      </div>

      <footer className="mt-auto shrink-0 px-4 py-6 border-t border-slate-800">
        <div className="max-w-xl mx-auto space-y-3">
          <div className="flex items-center gap-2 text-sm">
            <span className="w-2 h-2 rounded-full bg-green-500 animate-pulse" />
            <span className="text-slate-400">All Systems Operational</span>
          </div>
          <p className="text-slate-500 text-xs">
            © 2026 VerifEye — Truth Layer. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  )
}
